FROM node:14-alpine as react_build
ENV PATH /node_modules/.bin:$PATH
COPY ./client/package.json .
RUN yarn install
COPY ./client .
RUN yarn run build

FROM nginx:stable-alpine
COPY --from=react_build /build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
